name: Deploy to GitHub Pages (npm)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --prefix .app
      - name: Build
        run: npm run build --prefix .app
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .app/dist

  deploy:
    name: Deploy
    needs: setup
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
